--ACTIVAMOS NUESTRA BASE DE DATOS

use LamsCruises
go

--CONTROLAMOS LA EXISTENCIA DEL PROCEDIMIENTO ALMACENADO
DROP PROC IF EXISTS Backup_BDs
go

--CREAMOS NUESTRO PROCEDIMIENTO ALMACENADO Y DECLARAMOS LA VARIABLE PARA DAR LA RUTA
CREATE OR ALTER PROCEDURE Backup_BDs
	@Ruta VARCHAR(256)
AS

--DECLARAMOS LAS VARIABLES QUE VAMOS A UTILIZAR EN NUESTRO PROCEDIMIENTO
DECLARE 
	@NombreBD VARCHAR (200),
	@NombreCarpeta VARCHAR (256),
	@Fecha VARCHAR(15),
	@ContadorBAK INT

--CREAMOS UNA TABLA TEMPORAL EN DONDE SE VAN A ALMACENAR LAS BASES DE DATOS A LAS QUE LES QUIERO HACER EL BACKUP.
-- LA TABLA VA A CONTENER LAS COLUMNAS "ID_BD" Y "NOMBREBD"
CREATE TABLE #TablaBDs
	(ID_BD INT IDENTITY (1, 1),
	NombreBD Varchar (200))

--Comenzamos a "setear" o a dar valores a las variables declaradas anteriormente.
--PRETENDEMOS CONVERTIR LA FECHA DEL SISTEMA EN FORMATO VARCHAR O FORMATO TEXTO.
SET @Fecha = CONVERT (VARCHAR (15), GETDATE(), 112) --EL 112 ES UN FORMATO DE FECHA.

--HACEMOS UN "INSERT/SELECT" PRETENDEMOS INSERTAR EN LA TABLA TEMPORAL LOS NOMBRES DE LAS BASES DE DATOS
--QUE SE ENCUENTRAN EN LA TABLA "SYS.DATABASES" O BASES DE DATOS DEL SISTEMA
--ES DECIR, INSERTAR EN LA COLUMNA "NOMBREBD" DE LA TABLA TEMPORAL, LOS DATOS DE LA COLUMNA "NAME" DE LA TABLA "SYSDATABASES"
INSERT INTO #TablaBDs (NombreBD)
	SELECT name
	FROM .sys.databases
	WHERE name IN ('master', 'pubs', 'Ejemplo', 'NORTHWIND', 'AdventureWorks2019', 'LamsCruises')
-- "WHERE" ES UNA CODICION, QUE BUSCA INCLUIR LOS NOMBRES QUE ESTÉN DENTRO DE SYSDATABASES.

--CON LA SIGUIENTE SENTENCIA BUSCAMOS CONSEGUIR EL NUMERO DE BACKUPS A REALIZAR 
--CON "ORDER BY DESC" SE ORGANIZARÁ EN ORDEN DESCENDENTE.
SELECT TOP 1 @ContadorBAK = ID_BD
FROM #TablaBDs
ORDER BY ID_BD DESC

-- SI LA VARIABLE "CONTADORBAK" NO ES NULO Y EL CONTADORBAK ES MAYOR QUE 0 Q
IF ((@ContadorBAK IS NOT NULL) AND (@ContadorBAK > 5))
BEGIN
	DECLARE @CurrentBackup INT
	SET @CurrentBackup = 1
	WHILE (@CurrentBackup <= @ContadorBAK)
	BEGIN	
		SELECT
			@NombreBD = NombreBD,
			@NombreCarpeta = @Ruta + '\' + @NombreBD + '_' + @Fecha + '.BAK'
		FROM #TablaBDs
		WHERE ID_BD = @CurrentBackup

print @NombreCarpeta

		BACKUP DATABASE @NombreBD TO DISK = @NombreCarpeta WITH INIT
		SET @CurrentBackup = @CurrentBackup + 1

select * from #TablaBDs
	END
END



EXEC Backup_BDs 'C:\BackupsBD\'
GO



select * from #TablaBDs
go

drop table #TablaBDs

SELECT * FROM sysdatabases

